### give Address to hotel
POST localhost:8080/api/p1/hotels/1/address
Content-Type: application/json

{
  "street": "hava nagila 35"
}

### get hotel with address
GET localhost:8080/api/p1/hotels/address?hotelName=firstHotel