### post Image
POST http://localhost:8080/api/p1/image?hotel_name=Queen of Sheba Eilat
Content-Type: multipart/form-data;boundary=boundary


--boundary
Content-Disposition: form-data; name="image"; filename="Queen%20of%20Sheba%20Eilat.jpeg"

< /Users/Niv/Desktop/Queen%20of%20Sheba%20Eilat.jpg

//TODO : find how to upload a few images in one time.

### get image
GET http://localhost:8080/api/p1/image/info/{{name}}


